# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

acme_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: AcmeDemoBundle:Security:login }

acme_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check

api_articles:
    pattern:  /api/articles
    defaults: { _controller: AcmeDemoBundle:Api:articles }

api_user:
    pattern:  /api/user
    defaults: { _controller: AcmeDemoBundle:Api:user }